[project]
name = "contacts-tui"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.11.3",
    "textual>=3.1.1",
    "textual-dev>=1.7.0",
]
